### ISSUE TITLE
增加了一个将Java对象转换为JSON的函数，方便前端在模板中使用

### ISSUE THREAD

**Issue by sxpujs** [fex-team/fis-velocity-tools#7]
请参考https://github.com/sxpujs/fis-velocity-tools-update

主要就是JSONDirective这个类，个人感觉可以加到基础框架中。

**Comment by 2betop** [comment]
哈哈，其实这个功能在 jello 里面是通过一个 velocity tools 实现的！

```velocity
$jello.parseJson($object)
```

**Comment by 2betop** [comment]
说错了，是 jsonEncode

http://oak.baidu.com/jello-demo/velocity/jello

**Comment by sxpujs** [comment]
在velocity的模板文件中，$jello.jsonEncode($variable)这种方式不能用啊，怎么使用呢？

**Comment by 2betop** [comment]
你说的是 jello 环境里面不能用还是，集成到后端后不能用？

jello demo 就能用啊。

https://github.com/2betop/jello-demo/blob/master/page/examples/data.vm#L49

**Comment by sxpujs** [comment]
集成到后端不能用，我再看看吧，难道会跟jello版本有关，$jello这个对象都不存在。

**Comment by 2betop** [comment]
![image](https://cloud.githubusercontent.com/assets/2698393/8122390/c5c46758-10eb-11e5-98c6-de8ee53bc53d.png)

**Comment by sxpujs** [comment]
可以啦，厉害，非常感谢
